### ISSUE TITLE
Why is`isCreate=1` for opCREATE2 opcode?

### ISSUE THREAD

**Issue by 3for** [0xPolygonHermez/zkevm-rom#144]
From [https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/opcodes.zkasm#L3347](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/opcodes.zkasm#L3347), why is`isCreate=1` for opCREATE2 opcode? Then [https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/process-tx.zkasm#L391](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/process-tx.zkasm#L391), the line below `; check enough bytes to read in calldata` will never be executed?

**Comment by eigmax** [comment]
Below is my understanding:

A := isCreateContract (create a new contract),  B := isCreate(create a contract call context with incoming calldata).

```
readCode:
        $ => A                          :MLOAD(isCreateContract)
        0 - A                           :JMPN(readDeployBytecode)
                                        :JMP(readByteCode)

...

;; read calldata bytes of a deploy transaction and process them
readDeployBytecode:
        ; check transaction is a deploy transaction
        $ => B                          :MLOAD(isCreate)
        0 - B                           :JMPN(readDeployBytecodeCreate)
        ; check enough bytes to read in calldata
        $ => B                          :MLOAD(txCalldataLen)
        B - PC - 1                      :JMPN(defaultOpCode)
        $ => HASHPOS                    :MLOAD(dataStarts)
        HASHPOS + PC => HASHPOS
        $ => E                          :MLOAD(batchHashDataId)
        1 => D
        $ => RR                         :HASHK(E)
        ${eventLog(onOpcode(RR))}
        PC + 1 => PC
                                        :JMP(@mapping_opcodes + RR)
```
if A = 1,  then readDeployBytecode,  check if we create a new call (B ?= 1), if B = 1, so A == B, read the calldata and start the call.  if B is zero, A != B, begin to initialize the contract in EVM and then start the call.
if A = 0, the contract is not deployed, and should return error.

Feel free to correct.

**Comment by 3for** [comment]
In opCREATE:
```
1                   :MSTORE(isCreateContract)
1                   :MSTORE(isCreate)
```
and in opCREATE2:
```
1                   :MSTORE(isCreateContract)
1                   :MSTORE(isCreate)
1                   :MSTORE(isCreate2)
```
Seems not possible for `A=1 while B=0` case?
And actually, both CREATE and CREATE2 use the same`readDeployBytecodeCreate` to deploy contract?

**Comment by eigmax** [comment]
yes, the constructor should be called immediately when the contract deploying.

**Comment by krlosMata** [comment]
I will explain the flow of opcodes `CREATE` and `CREATE2` and their differences:
- `opCREATE`
  - `isCreateContract = 1`
  - `isCreate = 1`
- `opCREATE2`
  - `isCreateContract = 1`
  - `isCreate = 1`
  - `isCreate2 = 1`

>Notice that either `opCREATE` & `opCREATE2` finishes their execution (if everything is correct) with `:JMP(txType)`
- `txType` check if the tx involves a contract creation through the variable `isCreateContract`
  - therefore, both opcodes will jump to `getContractAddress`
- `getContractAddress` will compute the address of the smart contract that will be created. Here, we differentiate between `opCREATE` and `opCREATE2` with the variable `isCreate2` since the address is computed differently depending the opcode
  - after computing the address, it jumps to `deploy` where some checks are performed and then it jumps to `readCode`
- `readCode` will check `isCreateContract` variable in order ti differentiate from a regular call transaction or a deployment. Since both opcodes involves contract creation, it jumps to `readDeployBytecode`
- `readDeployBytecode` checks the variable `isCreate` which differentiate if the deployment comes from a deployment transaction (`to = 0x`) or the opcodes `opCREATE` or `opCREATE2`. Note that if the deployment comes form a transaction, the `calldata` is read in order to trigger the constructor code and get the contract code. If it comes from `opCREATE` or `opCREATE2`, data is read from memory (`readDeployBytecodeCreate`) according to offset and size specified when the opcode was called

**Comment by 3for** [comment]
Thanks a lot @krlosMata . Your explaination is great.
